kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: soyachaaps.dillichaaps.com
spec:
  group: dillichaaps.com
  names:
    plural: soyachaaps
    singular: soyachaap
    kind: SoyaChaap
    shortNames:
      - chaap
      - sch
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: "This is the type of chaap"
                bread:
                  type: string
                  description: "This is the type of roti you want"
---
kind: SoyaChaap
apiVersion: dillichaaps.com/v1
metadata:
  name: harshit-chaap
spec:
  name: malai-chaap
  bread: rumali-roti
